# Generated by Django 3.2.5 on 2023-02-22 08:00

import buswalaApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sbw_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('school_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=500)),
                ('pick_up_location', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('unique_business_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', buswalaApp.models.sbw_CustomerManager()),
            ],
        ),
    ]
