# Generated by Django 3.2.5 on 2023-03-03 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buswalaApp', '0003_sbw_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbw_driver',
            name='driver_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='sbw_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=50)),
                ('review_content', models.CharField(max_length=500)),
                ('review_rating', models.IntegerField(default=0)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buswalaApp.sbw_driver')),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
